package net.yiyuanda.web.bean;

public class AboutUs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about_us.about_id
     *
     * @mbg.generated
     */
    private Integer aboutId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about_us.about_describe
     *
     * @mbg.generated
     */
    private String aboutDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about_us.template_image
     *
     * @mbg.generated
     */
    private String templateImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about_us.tm_smp
     *
     * @mbg.generated
     */
    private String tmSmp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column about_us.about_id
     *
     * @return the value of about_us.about_id
     *
     * @mbg.generated
     */
    public Integer getAboutId() {
        return aboutId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column about_us.about_id
     *
     * @param aboutId the value for about_us.about_id
     *
     * @mbg.generated
     */
    public void setAboutId(Integer aboutId) {
        this.aboutId = aboutId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column about_us.about_describe
     *
     * @return the value of about_us.about_describe
     *
     * @mbg.generated
     */
    public String getAboutDescribe() {
        return aboutDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column about_us.about_describe
     *
     * @param aboutDescribe the value for about_us.about_describe
     *
     * @mbg.generated
     */
    public void setAboutDescribe(String aboutDescribe) {
        this.aboutDescribe = aboutDescribe == null ? null : aboutDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column about_us.template_image
     *
     * @return the value of about_us.template_image
     *
     * @mbg.generated
     */
    public String getTemplateImage() {
        return templateImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column about_us.template_image
     *
     * @param templateImage the value for about_us.template_image
     *
     * @mbg.generated
     */
    public void setTemplateImage(String templateImage) {
        this.templateImage = templateImage == null ? null : templateImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column about_us.tm_smp
     *
     * @return the value of about_us.tm_smp
     *
     * @mbg.generated
     */
    public String getTmSmp() {
        return tmSmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column about_us.tm_smp
     *
     * @param tmSmp the value for about_us.tm_smp
     *
     * @mbg.generated
     */
    public void setTmSmp(String tmSmp) {
        this.tmSmp = tmSmp == null ? null : tmSmp.trim();
    }
}