package net.yiyuanda.web.bean;

public class AdmissionListInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admission_list_info.admission_id
     *
     * @mbg.generated
     */
    private Integer admissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admission_list_info.admission_major
     *
     * @mbg.generated
     */
    private String admissionMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admission_list_info.admission_title
     *
     * @mbg.generated
     */
    private String admissionTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admission_list_info.admission_describe
     *
     * @mbg.generated
     */
    private String admissionDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admission_list_info.admission_image
     *
     * @mbg.generated
     */
    private String admissionImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admission_list_info.tm_smp
     *
     * @mbg.generated
     */
    private String tmSmp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admission_list_info.admission_id
     *
     * @return the value of admission_list_info.admission_id
     *
     * @mbg.generated
     */
    public Integer getAdmissionId() {
        return admissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admission_list_info.admission_id
     *
     * @param admissionId the value for admission_list_info.admission_id
     *
     * @mbg.generated
     */
    public void setAdmissionId(Integer admissionId) {
        this.admissionId = admissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admission_list_info.admission_major
     *
     * @return the value of admission_list_info.admission_major
     *
     * @mbg.generated
     */
    public String getAdmissionMajor() {
        return admissionMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admission_list_info.admission_major
     *
     * @param admissionMajor the value for admission_list_info.admission_major
     *
     * @mbg.generated
     */
    public void setAdmissionMajor(String admissionMajor) {
        this.admissionMajor = admissionMajor == null ? null : admissionMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admission_list_info.admission_title
     *
     * @return the value of admission_list_info.admission_title
     *
     * @mbg.generated
     */
    public String getAdmissionTitle() {
        return admissionTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admission_list_info.admission_title
     *
     * @param admissionTitle the value for admission_list_info.admission_title
     *
     * @mbg.generated
     */
    public void setAdmissionTitle(String admissionTitle) {
        this.admissionTitle = admissionTitle == null ? null : admissionTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admission_list_info.admission_describe
     *
     * @return the value of admission_list_info.admission_describe
     *
     * @mbg.generated
     */
    public String getAdmissionDescribe() {
        return admissionDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admission_list_info.admission_describe
     *
     * @param admissionDescribe the value for admission_list_info.admission_describe
     *
     * @mbg.generated
     */
    public void setAdmissionDescribe(String admissionDescribe) {
        this.admissionDescribe = admissionDescribe == null ? null : admissionDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admission_list_info.admission_image
     *
     * @return the value of admission_list_info.admission_image
     *
     * @mbg.generated
     */
    public String getAdmissionImage() {
        return admissionImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admission_list_info.admission_image
     *
     * @param admissionImage the value for admission_list_info.admission_image
     *
     * @mbg.generated
     */
    public void setAdmissionImage(String admissionImage) {
        this.admissionImage = admissionImage == null ? null : admissionImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admission_list_info.tm_smp
     *
     * @return the value of admission_list_info.tm_smp
     *
     * @mbg.generated
     */
    public String getTmSmp() {
        return tmSmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admission_list_info.tm_smp
     *
     * @param tmSmp the value for admission_list_info.tm_smp
     *
     * @mbg.generated
     */
    public void setTmSmp(String tmSmp) {
        this.tmSmp = tmSmp == null ? null : tmSmp.trim();
    }
}