package net.yiyuanda.web.bean;

public class BaoYanDryGood {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bao_yan_dry_good.good_id
     *
     * @mbg.generated
     */
    private Integer goodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bao_yan_dry_good.good_title
     *
     * @mbg.generated
     */
    private String goodTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bao_yan_dry_good.good_type
     *
     * @mbg.generated
     */
    private String goodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bao_yan_dry_good.good_describe
     *
     * @mbg.generated
     */
    private String goodDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bao_yan_dry_good.good_image
     *
     * @mbg.generated
     */
    private String goodImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bao_yan_dry_good.tm_smp
     *
     * @mbg.generated
     */
    private String tmSmp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bao_yan_dry_good.good_id
     *
     * @return the value of bao_yan_dry_good.good_id
     *
     * @mbg.generated
     */
    public Integer getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bao_yan_dry_good.good_id
     *
     * @param goodId the value for bao_yan_dry_good.good_id
     *
     * @mbg.generated
     */
    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bao_yan_dry_good.good_title
     *
     * @return the value of bao_yan_dry_good.good_title
     *
     * @mbg.generated
     */
    public String getGoodTitle() {
        return goodTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bao_yan_dry_good.good_title
     *
     * @param goodTitle the value for bao_yan_dry_good.good_title
     *
     * @mbg.generated
     */
    public void setGoodTitle(String goodTitle) {
        this.goodTitle = goodTitle == null ? null : goodTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bao_yan_dry_good.good_type
     *
     * @return the value of bao_yan_dry_good.good_type
     *
     * @mbg.generated
     */
    public String getGoodType() {
        return goodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bao_yan_dry_good.good_type
     *
     * @param goodType the value for bao_yan_dry_good.good_type
     *
     * @mbg.generated
     */
    public void setGoodType(String goodType) {
        this.goodType = goodType == null ? null : goodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bao_yan_dry_good.good_describe
     *
     * @return the value of bao_yan_dry_good.good_describe
     *
     * @mbg.generated
     */
    public String getGoodDescribe() {
        return goodDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bao_yan_dry_good.good_describe
     *
     * @param goodDescribe the value for bao_yan_dry_good.good_describe
     *
     * @mbg.generated
     */
    public void setGoodDescribe(String goodDescribe) {
        this.goodDescribe = goodDescribe == null ? null : goodDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bao_yan_dry_good.good_image
     *
     * @return the value of bao_yan_dry_good.good_image
     *
     * @mbg.generated
     */
    public String getGoodImage() {
        return goodImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bao_yan_dry_good.good_image
     *
     * @param goodImage the value for bao_yan_dry_good.good_image
     *
     * @mbg.generated
     */
    public void setGoodImage(String goodImage) {
        this.goodImage = goodImage == null ? null : goodImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bao_yan_dry_good.tm_smp
     *
     * @return the value of bao_yan_dry_good.tm_smp
     *
     * @mbg.generated
     */
    public String getTmSmp() {
        return tmSmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bao_yan_dry_good.tm_smp
     *
     * @param tmSmp the value for bao_yan_dry_good.tm_smp
     *
     * @mbg.generated
     */
    public void setTmSmp(String tmSmp) {
        this.tmSmp = tmSmp == null ? null : tmSmp.trim();
    }
}