package net.yiyuanda.web.bean;

public class BigData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data.big_id
     *
     * @mbg.generated
     */
    private Integer bigId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data.big_major
     *
     * @mbg.generated
     */
    private String bigMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data.big_title
     *
     * @mbg.generated
     */
    private String bigTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data.big_describe
     *
     * @mbg.generated
     */
    private String bigDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data.big_image
     *
     * @mbg.generated
     */
    private String bigImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big_data.tm_smp
     *
     * @mbg.generated
     */
    private String tmSmp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data.big_id
     *
     * @return the value of big_data.big_id
     *
     * @mbg.generated
     */
    public Integer getBigId() {
        return bigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data.big_id
     *
     * @param bigId the value for big_data.big_id
     *
     * @mbg.generated
     */
    public void setBigId(Integer bigId) {
        this.bigId = bigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data.big_major
     *
     * @return the value of big_data.big_major
     *
     * @mbg.generated
     */
    public String getBigMajor() {
        return bigMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data.big_major
     *
     * @param bigMajor the value for big_data.big_major
     *
     * @mbg.generated
     */
    public void setBigMajor(String bigMajor) {
        this.bigMajor = bigMajor == null ? null : bigMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data.big_title
     *
     * @return the value of big_data.big_title
     *
     * @mbg.generated
     */
    public String getBigTitle() {
        return bigTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data.big_title
     *
     * @param bigTitle the value for big_data.big_title
     *
     * @mbg.generated
     */
    public void setBigTitle(String bigTitle) {
        this.bigTitle = bigTitle == null ? null : bigTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data.big_describe
     *
     * @return the value of big_data.big_describe
     *
     * @mbg.generated
     */
    public String getBigDescribe() {
        return bigDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data.big_describe
     *
     * @param bigDescribe the value for big_data.big_describe
     *
     * @mbg.generated
     */
    public void setBigDescribe(String bigDescribe) {
        this.bigDescribe = bigDescribe == null ? null : bigDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data.big_image
     *
     * @return the value of big_data.big_image
     *
     * @mbg.generated
     */
    public String getBigImage() {
        return bigImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data.big_image
     *
     * @param bigImage the value for big_data.big_image
     *
     * @mbg.generated
     */
    public void setBigImage(String bigImage) {
        this.bigImage = bigImage == null ? null : bigImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big_data.tm_smp
     *
     * @return the value of big_data.tm_smp
     *
     * @mbg.generated
     */
    public String getTmSmp() {
        return tmSmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big_data.tm_smp
     *
     * @param tmSmp the value for big_data.tm_smp
     *
     * @mbg.generated
     */
    public void setTmSmp(String tmSmp) {
        this.tmSmp = tmSmp == null ? null : tmSmp.trim();
    }
}