package net.yiyuanda.web.bean;

import java.math.BigDecimal;

public class Coach {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.coach_id
     *
     * @mbg.generated
     */
    private Integer coachId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.coach_title
     *
     * @mbg.generated
     */
    private String coachTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.coach_type
     *
     * @mbg.generated
     */
    private String coachType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.coach_describe
     *
     * @mbg.generated
     */
    private String coachDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.coach_image
     *
     * @mbg.generated
     */
    private String coachImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.coach_historical_price
     *
     * @mbg.generated
     */
    private BigDecimal coachHistoricalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.coach_price
     *
     * @mbg.generated
     */
    private BigDecimal coachPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.coach_number
     *
     * @mbg.generated
     */
    private String coachNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.tm_smp
     *
     * @mbg.generated
     */
    private String tmSmp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.coach_id
     *
     * @return the value of coach.coach_id
     *
     * @mbg.generated
     */
    public Integer getCoachId() {
        return coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.coach_id
     *
     * @param coachId the value for coach.coach_id
     *
     * @mbg.generated
     */
    public void setCoachId(Integer coachId) {
        this.coachId = coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.coach_title
     *
     * @return the value of coach.coach_title
     *
     * @mbg.generated
     */
    public String getCoachTitle() {
        return coachTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.coach_title
     *
     * @param coachTitle the value for coach.coach_title
     *
     * @mbg.generated
     */
    public void setCoachTitle(String coachTitle) {
        this.coachTitle = coachTitle == null ? null : coachTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.coach_type
     *
     * @return the value of coach.coach_type
     *
     * @mbg.generated
     */
    public String getCoachType() {
        return coachType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.coach_type
     *
     * @param coachType the value for coach.coach_type
     *
     * @mbg.generated
     */
    public void setCoachType(String coachType) {
        this.coachType = coachType == null ? null : coachType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.coach_describe
     *
     * @return the value of coach.coach_describe
     *
     * @mbg.generated
     */
    public String getCoachDescribe() {
        return coachDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.coach_describe
     *
     * @param coachDescribe the value for coach.coach_describe
     *
     * @mbg.generated
     */
    public void setCoachDescribe(String coachDescribe) {
        this.coachDescribe = coachDescribe == null ? null : coachDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.coach_image
     *
     * @return the value of coach.coach_image
     *
     * @mbg.generated
     */
    public String getCoachImage() {
        return coachImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.coach_image
     *
     * @param coachImage the value for coach.coach_image
     *
     * @mbg.generated
     */
    public void setCoachImage(String coachImage) {
        this.coachImage = coachImage == null ? null : coachImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.coach_historical_price
     *
     * @return the value of coach.coach_historical_price
     *
     * @mbg.generated
     */
    public BigDecimal getCoachHistoricalPrice() {
        return coachHistoricalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.coach_historical_price
     *
     * @param coachHistoricalPrice the value for coach.coach_historical_price
     *
     * @mbg.generated
     */
    public void setCoachHistoricalPrice(BigDecimal coachHistoricalPrice) {
        this.coachHistoricalPrice = coachHistoricalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.coach_price
     *
     * @return the value of coach.coach_price
     *
     * @mbg.generated
     */
    public BigDecimal getCoachPrice() {
        return coachPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.coach_price
     *
     * @param coachPrice the value for coach.coach_price
     *
     * @mbg.generated
     */
    public void setCoachPrice(BigDecimal coachPrice) {
        this.coachPrice = coachPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.coach_number
     *
     * @return the value of coach.coach_number
     *
     * @mbg.generated
     */
    public String getCoachNumber() {
        return coachNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.coach_number
     *
     * @param coachNumber the value for coach.coach_number
     *
     * @mbg.generated
     */
    public void setCoachNumber(String coachNumber) {
        this.coachNumber = coachNumber == null ? null : coachNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.tm_smp
     *
     * @return the value of coach.tm_smp
     *
     * @mbg.generated
     */
    public String getTmSmp() {
        return tmSmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.tm_smp
     *
     * @param tmSmp the value for coach.tm_smp
     *
     * @mbg.generated
     */
    public void setTmSmp(String tmSmp) {
        this.tmSmp = tmSmp == null ? null : tmSmp.trim();
    }
}