package net.yiyuanda.web.bean;

public class PrePushInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_push_info.pre_id
     *
     * @mbg.generated
     */
    private Integer preId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_push_info.pre_major
     *
     * @mbg.generated
     */
    private String preMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_push_info.pre_title
     *
     * @mbg.generated
     */
    private String preTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_push_info.pre_describe
     *
     * @mbg.generated
     */
    private String preDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_push_info.pre_image
     *
     * @mbg.generated
     */
    private String preImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_push_info.pre_school
     *
     * @mbg.generated
     */
    private String preSchool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_push_info.tm_smp
     *
     * @mbg.generated
     */
    private String tmSmp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_push_info.pre_id
     *
     * @return the value of pre_push_info.pre_id
     *
     * @mbg.generated
     */
    public Integer getPreId() {
        return preId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_push_info.pre_id
     *
     * @param preId the value for pre_push_info.pre_id
     *
     * @mbg.generated
     */
    public void setPreId(Integer preId) {
        this.preId = preId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_push_info.pre_major
     *
     * @return the value of pre_push_info.pre_major
     *
     * @mbg.generated
     */
    public String getPreMajor() {
        return preMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_push_info.pre_major
     *
     * @param preMajor the value for pre_push_info.pre_major
     *
     * @mbg.generated
     */
    public void setPreMajor(String preMajor) {
        this.preMajor = preMajor == null ? null : preMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_push_info.pre_title
     *
     * @return the value of pre_push_info.pre_title
     *
     * @mbg.generated
     */
    public String getPreTitle() {
        return preTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_push_info.pre_title
     *
     * @param preTitle the value for pre_push_info.pre_title
     *
     * @mbg.generated
     */
    public void setPreTitle(String preTitle) {
        this.preTitle = preTitle == null ? null : preTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_push_info.pre_describe
     *
     * @return the value of pre_push_info.pre_describe
     *
     * @mbg.generated
     */
    public String getPreDescribe() {
        return preDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_push_info.pre_describe
     *
     * @param preDescribe the value for pre_push_info.pre_describe
     *
     * @mbg.generated
     */
    public void setPreDescribe(String preDescribe) {
        this.preDescribe = preDescribe == null ? null : preDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_push_info.pre_image
     *
     * @return the value of pre_push_info.pre_image
     *
     * @mbg.generated
     */
    public String getPreImage() {
        return preImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_push_info.pre_image
     *
     * @param preImage the value for pre_push_info.pre_image
     *
     * @mbg.generated
     */
    public void setPreImage(String preImage) {
        this.preImage = preImage == null ? null : preImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_push_info.pre_school
     *
     * @return the value of pre_push_info.pre_school
     *
     * @mbg.generated
     */
    public String getPreSchool() {
        return preSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_push_info.pre_school
     *
     * @param preSchool the value for pre_push_info.pre_school
     *
     * @mbg.generated
     */
    public void setPreSchool(String preSchool) {
        this.preSchool = preSchool == null ? null : preSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_push_info.tm_smp
     *
     * @return the value of pre_push_info.tm_smp
     *
     * @mbg.generated
     */
    public String getTmSmp() {
        return tmSmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_push_info.tm_smp
     *
     * @param tmSmp the value for pre_push_info.tm_smp
     *
     * @mbg.generated
     */
    public void setTmSmp(String tmSmp) {
        this.tmSmp = tmSmp == null ? null : tmSmp.trim();
    }
}