package net.yiyuanda.web.bean;

public class RealExperience {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column real_experience.real_id
     *
     * @mbg.generated
     */
    private Integer realId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column real_experience.real_major
     *
     * @mbg.generated
     */
    private String realMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column real_experience.real_title
     *
     * @mbg.generated
     */
    private String realTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column real_experience.real_describe
     *
     * @mbg.generated
     */
    private String realDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column real_experience.real_image
     *
     * @mbg.generated
     */
    private String realImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column real_experience.tm_smp
     *
     * @mbg.generated
     */
    private String tmSmp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column real_experience.real_id
     *
     * @return the value of real_experience.real_id
     *
     * @mbg.generated
     */
    public Integer getRealId() {
        return realId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column real_experience.real_id
     *
     * @param realId the value for real_experience.real_id
     *
     * @mbg.generated
     */
    public void setRealId(Integer realId) {
        this.realId = realId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column real_experience.real_major
     *
     * @return the value of real_experience.real_major
     *
     * @mbg.generated
     */
    public String getRealMajor() {
        return realMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column real_experience.real_major
     *
     * @param realMajor the value for real_experience.real_major
     *
     * @mbg.generated
     */
    public void setRealMajor(String realMajor) {
        this.realMajor = realMajor == null ? null : realMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column real_experience.real_title
     *
     * @return the value of real_experience.real_title
     *
     * @mbg.generated
     */
    public String getRealTitle() {
        return realTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column real_experience.real_title
     *
     * @param realTitle the value for real_experience.real_title
     *
     * @mbg.generated
     */
    public void setRealTitle(String realTitle) {
        this.realTitle = realTitle == null ? null : realTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column real_experience.real_describe
     *
     * @return the value of real_experience.real_describe
     *
     * @mbg.generated
     */
    public String getRealDescribe() {
        return realDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column real_experience.real_describe
     *
     * @param realDescribe the value for real_experience.real_describe
     *
     * @mbg.generated
     */
    public void setRealDescribe(String realDescribe) {
        this.realDescribe = realDescribe == null ? null : realDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column real_experience.real_image
     *
     * @return the value of real_experience.real_image
     *
     * @mbg.generated
     */
    public String getRealImage() {
        return realImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column real_experience.real_image
     *
     * @param realImage the value for real_experience.real_image
     *
     * @mbg.generated
     */
    public void setRealImage(String realImage) {
        this.realImage = realImage == null ? null : realImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column real_experience.tm_smp
     *
     * @return the value of real_experience.tm_smp
     *
     * @mbg.generated
     */
    public String getTmSmp() {
        return tmSmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column real_experience.tm_smp
     *
     * @param tmSmp the value for real_experience.tm_smp
     *
     * @mbg.generated
     */
    public void setTmSmp(String tmSmp) {
        this.tmSmp = tmSmp == null ? null : tmSmp.trim();
    }
}