package net.yiyuanda.web.bean;

public class SummerCampInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summer_camp_info.summer_id
     *
     * @mbg.generated
     */
    private Integer summerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summer_camp_info.summer_major
     *
     * @mbg.generated
     */
    private String summerMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summer_camp_info.summer_title
     *
     * @mbg.generated
     */
    private String summerTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summer_camp_info.summer_describe
     *
     * @mbg.generated
     */
    private String summerDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summer_camp_info.summer_image
     *
     * @mbg.generated
     */
    private String summerImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summer_camp_info.summer_school
     *
     * @mbg.generated
     */
    private String summerSchool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summer_camp_info.tm_smp
     *
     * @mbg.generated
     */
    private String tmSmp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summer_camp_info.summer_id
     *
     * @return the value of summer_camp_info.summer_id
     *
     * @mbg.generated
     */
    public Integer getSummerId() {
        return summerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summer_camp_info.summer_id
     *
     * @param summerId the value for summer_camp_info.summer_id
     *
     * @mbg.generated
     */
    public void setSummerId(Integer summerId) {
        this.summerId = summerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summer_camp_info.summer_major
     *
     * @return the value of summer_camp_info.summer_major
     *
     * @mbg.generated
     */
    public String getSummerMajor() {
        return summerMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summer_camp_info.summer_major
     *
     * @param summerMajor the value for summer_camp_info.summer_major
     *
     * @mbg.generated
     */
    public void setSummerMajor(String summerMajor) {
        this.summerMajor = summerMajor == null ? null : summerMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summer_camp_info.summer_title
     *
     * @return the value of summer_camp_info.summer_title
     *
     * @mbg.generated
     */
    public String getSummerTitle() {
        return summerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summer_camp_info.summer_title
     *
     * @param summerTitle the value for summer_camp_info.summer_title
     *
     * @mbg.generated
     */
    public void setSummerTitle(String summerTitle) {
        this.summerTitle = summerTitle == null ? null : summerTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summer_camp_info.summer_describe
     *
     * @return the value of summer_camp_info.summer_describe
     *
     * @mbg.generated
     */
    public String getSummerDescribe() {
        return summerDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summer_camp_info.summer_describe
     *
     * @param summerDescribe the value for summer_camp_info.summer_describe
     *
     * @mbg.generated
     */
    public void setSummerDescribe(String summerDescribe) {
        this.summerDescribe = summerDescribe == null ? null : summerDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summer_camp_info.summer_image
     *
     * @return the value of summer_camp_info.summer_image
     *
     * @mbg.generated
     */
    public String getSummerImage() {
        return summerImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summer_camp_info.summer_image
     *
     * @param summerImage the value for summer_camp_info.summer_image
     *
     * @mbg.generated
     */
    public void setSummerImage(String summerImage) {
        this.summerImage = summerImage == null ? null : summerImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summer_camp_info.summer_school
     *
     * @return the value of summer_camp_info.summer_school
     *
     * @mbg.generated
     */
    public String getSummerSchool() {
        return summerSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summer_camp_info.summer_school
     *
     * @param summerSchool the value for summer_camp_info.summer_school
     *
     * @mbg.generated
     */
    public void setSummerSchool(String summerSchool) {
        this.summerSchool = summerSchool == null ? null : summerSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summer_camp_info.tm_smp
     *
     * @return the value of summer_camp_info.tm_smp
     *
     * @mbg.generated
     */
    public String getTmSmp() {
        return tmSmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summer_camp_info.tm_smp
     *
     * @param tmSmp the value for summer_camp_info.tm_smp
     *
     * @mbg.generated
     */
    public void setTmSmp(String tmSmp) {
        this.tmSmp = tmSmp == null ? null : tmSmp.trim();
    }
}