package net.yiyuanda.web.bean;

public class Template {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.template_id
     *
     * @mbg.generated
     */
    private Integer templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.template_title
     *
     * @mbg.generated
     */
    private String templateTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.template_type
     *
     * @mbg.generated
     */
    private String templateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.template_describe
     *
     * @mbg.generated
     */
    private String templateDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.template_image
     *
     * @mbg.generated
     */
    private String templateImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.tm_smp
     *
     * @mbg.generated
     */
    private String tmSmp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.template_id
     *
     * @return the value of template.template_id
     *
     * @mbg.generated
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.template_id
     *
     * @param templateId the value for template.template_id
     *
     * @mbg.generated
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.template_title
     *
     * @return the value of template.template_title
     *
     * @mbg.generated
     */
    public String getTemplateTitle() {
        return templateTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.template_title
     *
     * @param templateTitle the value for template.template_title
     *
     * @mbg.generated
     */
    public void setTemplateTitle(String templateTitle) {
        this.templateTitle = templateTitle == null ? null : templateTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.template_type
     *
     * @return the value of template.template_type
     *
     * @mbg.generated
     */
    public String getTemplateType() {
        return templateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.template_type
     *
     * @param templateType the value for template.template_type
     *
     * @mbg.generated
     */
    public void setTemplateType(String templateType) {
        this.templateType = templateType == null ? null : templateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.template_describe
     *
     * @return the value of template.template_describe
     *
     * @mbg.generated
     */
    public String getTemplateDescribe() {
        return templateDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.template_describe
     *
     * @param templateDescribe the value for template.template_describe
     *
     * @mbg.generated
     */
    public void setTemplateDescribe(String templateDescribe) {
        this.templateDescribe = templateDescribe == null ? null : templateDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.template_image
     *
     * @return the value of template.template_image
     *
     * @mbg.generated
     */
    public String getTemplateImage() {
        return templateImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.template_image
     *
     * @param templateImage the value for template.template_image
     *
     * @mbg.generated
     */
    public void setTemplateImage(String templateImage) {
        this.templateImage = templateImage == null ? null : templateImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.tm_smp
     *
     * @return the value of template.tm_smp
     *
     * @mbg.generated
     */
    public String getTmSmp() {
        return tmSmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.tm_smp
     *
     * @param tmSmp the value for template.tm_smp
     *
     * @mbg.generated
     */
    public void setTmSmp(String tmSmp) {
        this.tmSmp = tmSmp == null ? null : tmSmp.trim();
    }
}