package net.yiyuanda.web.bean;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_phone
     *
     * @mbg.generated
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_head_image
     *
     * @mbg.generated
     */
    private String userHeadImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_major
     *
     * @mbg.generated
     */
    private String userMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_account_name
     *
     * @mbg.generated
     */
    private String userAccountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_wechat_number
     *
     * @mbg.generated
     */
    private String userWechatNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_school
     *
     * @mbg.generated
     */
    private String userSchool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_college_major
     *
     * @mbg.generated
     */
    private String userCollegeMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_entrance_grade
     *
     * @mbg.generated
     */
    private String userEntranceGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_scientific_research
     *
     * @mbg.generated
     */
    private String userScientificResearch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_honorary_award
     *
     * @mbg.generated
     */
    private String userHonoraryAward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_practical_activity
     *
     * @mbg.generated
     */
    private String userPracticalActivity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_login_password
     *
     * @mbg.generated
     */
    private String userLoginPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.tm_smp
     *
     * @mbg.generated
     */
    private String tmSmp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_phone
     *
     * @return the value of user_info.user_phone
     *
     * @mbg.generated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_phone
     *
     * @param userPhone the value for user_info.user_phone
     *
     * @mbg.generated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_head_image
     *
     * @return the value of user_info.user_head_image
     *
     * @mbg.generated
     */
    public String getUserHeadImage() {
        return userHeadImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_head_image
     *
     * @param userHeadImage the value for user_info.user_head_image
     *
     * @mbg.generated
     */
    public void setUserHeadImage(String userHeadImage) {
        this.userHeadImage = userHeadImage == null ? null : userHeadImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_major
     *
     * @return the value of user_info.user_major
     *
     * @mbg.generated
     */
    public String getUserMajor() {
        return userMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_major
     *
     * @param userMajor the value for user_info.user_major
     *
     * @mbg.generated
     */
    public void setUserMajor(String userMajor) {
        this.userMajor = userMajor == null ? null : userMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_account_name
     *
     * @return the value of user_info.user_account_name
     *
     * @mbg.generated
     */
    public String getUserAccountName() {
        return userAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_account_name
     *
     * @param userAccountName the value for user_info.user_account_name
     *
     * @mbg.generated
     */
    public void setUserAccountName(String userAccountName) {
        this.userAccountName = userAccountName == null ? null : userAccountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_wechat_number
     *
     * @return the value of user_info.user_wechat_number
     *
     * @mbg.generated
     */
    public String getUserWechatNumber() {
        return userWechatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_wechat_number
     *
     * @param userWechatNumber the value for user_info.user_wechat_number
     *
     * @mbg.generated
     */
    public void setUserWechatNumber(String userWechatNumber) {
        this.userWechatNumber = userWechatNumber == null ? null : userWechatNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_school
     *
     * @return the value of user_info.user_school
     *
     * @mbg.generated
     */
    public String getUserSchool() {
        return userSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_school
     *
     * @param userSchool the value for user_info.user_school
     *
     * @mbg.generated
     */
    public void setUserSchool(String userSchool) {
        this.userSchool = userSchool == null ? null : userSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_college_major
     *
     * @return the value of user_info.user_college_major
     *
     * @mbg.generated
     */
    public String getUserCollegeMajor() {
        return userCollegeMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_college_major
     *
     * @param userCollegeMajor the value for user_info.user_college_major
     *
     * @mbg.generated
     */
    public void setUserCollegeMajor(String userCollegeMajor) {
        this.userCollegeMajor = userCollegeMajor == null ? null : userCollegeMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_entrance_grade
     *
     * @return the value of user_info.user_entrance_grade
     *
     * @mbg.generated
     */
    public String getUserEntranceGrade() {
        return userEntranceGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_entrance_grade
     *
     * @param userEntranceGrade the value for user_info.user_entrance_grade
     *
     * @mbg.generated
     */
    public void setUserEntranceGrade(String userEntranceGrade) {
        this.userEntranceGrade = userEntranceGrade == null ? null : userEntranceGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_scientific_research
     *
     * @return the value of user_info.user_scientific_research
     *
     * @mbg.generated
     */
    public String getUserScientificResearch() {
        return userScientificResearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_scientific_research
     *
     * @param userScientificResearch the value for user_info.user_scientific_research
     *
     * @mbg.generated
     */
    public void setUserScientificResearch(String userScientificResearch) {
        this.userScientificResearch = userScientificResearch == null ? null : userScientificResearch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_honorary_award
     *
     * @return the value of user_info.user_honorary_award
     *
     * @mbg.generated
     */
    public String getUserHonoraryAward() {
        return userHonoraryAward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_honorary_award
     *
     * @param userHonoraryAward the value for user_info.user_honorary_award
     *
     * @mbg.generated
     */
    public void setUserHonoraryAward(String userHonoraryAward) {
        this.userHonoraryAward = userHonoraryAward == null ? null : userHonoraryAward.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_practical_activity
     *
     * @return the value of user_info.user_practical_activity
     *
     * @mbg.generated
     */
    public String getUserPracticalActivity() {
        return userPracticalActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_practical_activity
     *
     * @param userPracticalActivity the value for user_info.user_practical_activity
     *
     * @mbg.generated
     */
    public void setUserPracticalActivity(String userPracticalActivity) {
        this.userPracticalActivity = userPracticalActivity == null ? null : userPracticalActivity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_login_password
     *
     * @return the value of user_info.user_login_password
     *
     * @mbg.generated
     */
    public String getUserLoginPassword() {
        return userLoginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_login_password
     *
     * @param userLoginPassword the value for user_info.user_login_password
     *
     * @mbg.generated
     */
    public void setUserLoginPassword(String userLoginPassword) {
        this.userLoginPassword = userLoginPassword == null ? null : userLoginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.tm_smp
     *
     * @return the value of user_info.tm_smp
     *
     * @mbg.generated
     */
    public String getTmSmp() {
        return tmSmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.tm_smp
     *
     * @param tmSmp the value for user_info.tm_smp
     *
     * @mbg.generated
     */
    public void setTmSmp(String tmSmp) {
        this.tmSmp = tmSmp == null ? null : tmSmp.trim();
    }
}