/*
package net.yiyuanda.web.dao;

import net.yiyuanda.web.bean.AboutUs;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface AboutUsMapper {


    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_us
     *
     * @mbg.generated
     *//*

    int deleteByPrimaryKey(Integer aboutId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_us
     *
     * @mbg.generated
     *//*

    int insert(AboutUs record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_us
     *
     * @mbg.generated
     *//*

    int insertSelective(AboutUs record);


    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_us
     *
     * @mbg.generated
     *//*

    AboutUs selectByPrimaryKey(Integer aboutId);


    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_us
     *
     * @mbg.generated
     *//*

    List<AboutUs> selectAll();

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_us
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKeySelective(AboutUs record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_us
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKey(AboutUs record);
}
*/
