/*
package net.yiyuanda.web.dao;

import java.util.List;
import net.yiyuanda.web.bean.AdmissionListInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AdmissionListInfoMapper {

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_list_info
     *
     * @mbg.generated
     *//*

    int deleteByPrimaryKey(Integer admissionId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_list_info
     *
     * @mbg.generated
     *//*

    int insert(AdmissionListInfo record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_list_info
     *
     * @mbg.generated
     *//*

    int insertSelective(AdmissionListInfo record);


    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_list_info
     *
     * @mbg.generated
     *//*

    AdmissionListInfo selectByPrimaryKey(Integer admissionId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_list_info
     *
     * @mbg.generated
     *//*

    List<AdmissionListInfo> selectAll();

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_list_info
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKeySelective(AdmissionListInfo record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_list_info
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKey(AdmissionListInfo record);
}
*/
