/*
package net.yiyuanda.web.dao;

import java.util.List;
import net.yiyuanda.web.bean.BaoYanStory;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface BaoYanStoryMapper {



    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bao_yan_story
     *
     * @mbg.generated
     *//*

    int deleteByPrimaryKey(Integer storyId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bao_yan_story
     *
     * @mbg.generated
     *//*

    int insert(BaoYanStory record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bao_yan_story
     *
     * @mbg.generated
     *//*

    int insertSelective(BaoYanStory record);


    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bao_yan_story
     *
     * @mbg.generated
     *//*

    BaoYanStory selectByPrimaryKey(Integer storyId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bao_yan_story
     *
     * @mbg.generated
     *//*

    List<BaoYanStory> selectAll();

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bao_yan_story
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKeySelective(BaoYanStory record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bao_yan_story
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKey(BaoYanStory record);
}
*/
