/*
package net.yiyuanda.web.dao;

import java.util.List;
import net.yiyuanda.web.bean.BaoYanDryGood;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface BaoYanDryGoodMapper {


    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bao_yan_dry_good
     *
     * @mbg.generated
     *//*

    int deleteByPrimaryKey(Integer goodId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bao_yan_dry_good
     *
     * @mbg.generated
     *//*

    int insert(BaoYanDryGood record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bao_yan_dry_good
     *
     * @mbg.generated
     *//*

    int insertSelective(BaoYanDryGood record);


    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bao_yan_dry_good
     *
     * @mbg.generated
     *//*

    BaoYanDryGood selectByPrimaryKey(Integer goodId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bao_yan_dry_good
     *
     * @mbg.generated
     *//*

    List<BaoYanDryGood> selectAll();


    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bao_yan_dry_good
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKeySelective(BaoYanDryGood record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bao_yan_dry_good
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKey(BaoYanDryGood record);
}
*/
