/*
package net.yiyuanda.web.dao;

import java.util.List;
import net.yiyuanda.web.bean.BigData;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface BigDataMapper {


    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data
     *
     * @mbg.generated
     *//*

    int deleteByPrimaryKey(Integer bigId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data
     *
     * @mbg.generated
     *//*

    int insert(BigData record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data
     *
     * @mbg.generated
     *//*

    int insertSelective(BigData record);


    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data
     *
     * @mbg.generated
     *//*

    BigData selectByPrimaryKey(Integer bigId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data
     *
     * @mbg.generated
     *//*

    List<BigData> selectAll();

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKeySelective(BigData record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKey(BigData record);
}
*/
