/*
package net.yiyuanda.web.dao;

import java.util.List;
import net.yiyuanda.web.bean.Coach;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CoachMapper {

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbg.generated
     *//*

    int deleteByPrimaryKey(Integer coachId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbg.generated
     *//*

    int insert(Coach record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbg.generated
     *//*

    int insertSelective(Coach record);


    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbg.generated
     *//*

    Coach selectByPrimaryKey(Integer coachId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbg.generated
     *//*

    List<Coach> selectAll();
    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKeySelective(Coach record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKey(Coach record);
}
*/
