/*
package net.yiyuanda.web.dao;

import java.util.List;
import net.yiyuanda.web.bean.PrePushInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PrePushInfoMapper {

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_push_info
     *
     * @mbg.generated
     *//*

    int deleteByPrimaryKey(Integer preId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_push_info
     *
     * @mbg.generated
     *//*

    int insert(PrePushInfo record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_push_info
     *
     * @mbg.generated
     *//*

    int insertSelective(PrePushInfo record);


    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_push_info
     *
     * @mbg.generated
     *//*

    PrePushInfo selectByPrimaryKey(Integer preId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_push_info
     *
     * @mbg.generated
     *//*

    List<PrePushInfo> selectAll();

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_push_info
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKeySelective(PrePushInfo record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_push_info
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKey(PrePushInfo record);
}
*/
