/*
package net.yiyuanda.web.dao;

import java.util.List;
import net.yiyuanda.web.bean.RealExperience;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface RealExperienceMapper {

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_experience
     *
     * @mbg.generated
     *//*

    int deleteByPrimaryKey(Integer realId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_experience
     *
     * @mbg.generated
     *//*

    int insert(RealExperience record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_experience
     *
     * @mbg.generated
     *//*

    int insertSelective(RealExperience record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_experience
     *
     * @mbg.generated
     *//*

    RealExperience selectByPrimaryKey(Integer realId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_experience
     *
     * @mbg.generated
     *//*

    List<RealExperience> selectAll();
    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_experience
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKeySelective(RealExperience record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_experience
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKey(RealExperience record);
}
*/
