/*
package net.yiyuanda.web.dao;

import java.util.List;
import net.yiyuanda.web.bean.SummerCampInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SummerCampInfoMapper {

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summer_camp_info
     *
     * @mbg.generated
     *//*

    int deleteByPrimaryKey(Integer summerId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summer_camp_info
     *
     * @mbg.generated
     *//*

    int insert(SummerCampInfo record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summer_camp_info
     *
     * @mbg.generated
     *//*

    int insertSelective(SummerCampInfo record);


    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summer_camp_info
     *
     * @mbg.generated
     *//*

    SummerCampInfo selectByPrimaryKey(Integer summerId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summer_camp_info
     *
     * @mbg.generated
     *//*

    List<SummerCampInfo> selectAll();

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summer_camp_info
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKeySelective(SummerCampInfo record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summer_camp_info
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKey(SummerCampInfo record);
}
*/
