/*
package net.yiyuanda.web.dao;

import java.util.List;
import net.yiyuanda.web.bean.Template;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface TemplateMapper {

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated
     *//*

    int deleteByPrimaryKey(Integer templateId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated
     *//*

    int insert(Template record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated
     *//*

    int insertSelective(Template record);


    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated
     *//*

    Template selectByPrimaryKey(Integer templateId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated
     *//*

    List<Template> selectAll();

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKeySelective(Template record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKey(Template record);
}
*/
