/*
package net.yiyuanda.web.dao;

import java.util.List;
import net.yiyuanda.web.bean.UserInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface UserInfoMapper {

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     *//*

    int deleteByPrimaryKey(Integer userId);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     *//*

    int insert(UserInfo record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     *//*

    int insertSelective(UserInfo record);


    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     *//*

    UserInfo selectByPrimaryKey(Integer userId);


    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKeySelective(UserInfo record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     *//*

    int updateByPrimaryKey(UserInfo record);
}
*/
